export const _Categories = [
  {
    id: 1,
    name: 'Pizza',
    image: require('../assets/images/icons8-pizza-96.png'),
  },
  {
    id: 2,
    name: 'Burger',
    image: require('../assets/images/icons8-pizza-96.png'),
  },
  {
    id: 3,
    name: 'Italian',
    image: require('../assets/images/icons8-pizza-96.png'),
  },
  {
    id: 4,
    name: 'Chinese',
    image: require('../assets/images/icons8-pizza-96.png'),
  },
  {
    id: 5,
    name: 'Noodles',
    image: require('../assets/images/icons8-pizza-96.png'),
  },
  {
    id: 6,
    name: 'Sweets',
    image: require('../assets/images/icons8-pizza-96.png'),
  },
];

export const Featured = {
  id: 1,
  title: 'Hot and Spicy',
  description: 'descriptiondescriptiondescription',
  restaurants: [
    {
      id: 1,
      name: 'Papa Johns',
      image: require('../assets/images/pizza.jpg'),
      description: 'Hot and Spicy Pizzas',
      lng: 38.2145602,
      lat: -85.5324269,
      address: '434 second street',
      stars: 4,
      reviews: '4.4K',
      category: 'FastFood',
      dishes: [
        {
          id: 1,
          name: 'Pizza',
          description: 'Cheezy Garlic Pizza',
          price: 10,
          image: require('../assets/images/dishes2.jpeg'),
        },
        {
          id: 2,
          name: 'Pizza',
          description: 'Cheezy Garlic Pizza',
          price: 10,
          image: require('../assets/images/dishes2.jpeg'),
        },
        {
          id: 3,
          name: 'Pizza',
          description: 'Cheezy Garlic Pizza',
          price: 10,
          image: require('../assets/images/dishes2.jpeg'),
        },
      ],
    },
    {
      id: 2,
      name: 'Papa Johns',
      image: require('../assets/images/pizza.jpg'),
      description: 'Hot and Spicy Pizzas',
      lng: 38.2145602,
      lat: -85.5324269,
      address: '434 second street',
      stars: 4,
      reviews: '4.4K',
      category: 'FastFood',
      dishes: [
        {
          id: 1,
          name: 'Pizza',
          description: 'Cheezy Garlic Pizza',
          price: 10,
          image: require('../assets/images/dishes2.jpeg'),
        },
        {
          id: 2,
          name: 'Pizza',
          description: 'Cheezy Garlic Pizza',
          price: 10,
          image: require('../assets/images/dishes2.jpeg'),
        },
        {
          id: 3,
          name: 'Pizza',
          description: 'Cheezy Garlic Pizza',
          price: 10,
          image: require('../assets/images/dishes2.jpeg'),
        },
      ],
    },
    {
      id: 3,
      name: 'Papa Johns',
      image: require('../assets/images/pizza.jpg'),
      description: 'Hot and Spicy Pizzas',
      lng: 38.2145602,
      lat: -85.5324269,
      address: '434 second street',
      stars: 4,
      reviews: '4.4K',
      category: 'FastFood',
      dishes: [
        {
          id: 1,
          name: 'Pizza',
          description: 'Cheezy Garlic Pizza',
          price: 10,
          image: require('../assets/images/dishes2.jpeg'),
        },
        {
          id: 2,
          name: 'Pizza',
          description: 'Cheezy Garlic Pizza',
          price: 10,
          image: require('../assets/images/dishes2.jpeg'),
        },
        {
          id: 3,
          name: 'Pizza',
          description: 'Cheezy Garlic Pizza',
          price: 10,
          image: require('../assets/images/dishes2.jpeg'),
        },
      ],
    },
  ],
};
